#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* fraudapi
* Easily and directly scan and block fraudulent security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFraudDetectionResult
@end

@interface CMFraudDetectionResult : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* True if the document is clean, false if fraud threats were found [optional]
 */
@property(nonatomic) NSNumber* cleanResult;
/* Overall fraud risk level between 0.0 and 1.0 [optional]
 */
@property(nonatomic) NSNumber* fraudRiskLevel;
/* True if the document contains financial liability [optional]
 */
@property(nonatomic) NSNumber* containsFinancialLiability;
/* True if the document contains sensitive data collection from the recipient [optional]
 */
@property(nonatomic) NSNumber* containsSensitiveInformationCollection;
/* True if the document contains an asset transfer [optional]
 */
@property(nonatomic) NSNumber* containsAssetTransfer;
/* True if the document contains a purchase agreement [optional]
 */
@property(nonatomic) NSNumber* containsPurchaseAgreement;
/* True if the document contains an employment agreement [optional]
 */
@property(nonatomic) NSNumber* containsEmploymentAgreement;

@end
