#import <Foundation/Foundation.h>
#import "CMAdvancedFraudDetectionResult.h"
#import "CMFraudDetectionResult.h"
#import "CMApi.h"

/**
* fraudapi
* Easily and directly scan and block fraudulent security threats in input.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMFraudDetectionApi: NSObject <CMApi>

extern NSString* kCMFraudDetectionApiErrorDomain;
extern NSInteger kCMFraudDetectionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// AI Fraud Detection for Documents
/// Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
///
/// @param inputFile Input document, or photos of a document, to perform fraud detection on (optional)
/// 
///  code:200 message:"OK"
///
/// @return CMFraudDetectionResult*
-(NSURLSessionTask*) documentDetectFraudWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMFraudDetectionResult* output, NSError* error)) handler;


/// Advanced AI Fraud Detection for Documents
/// Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
///
/// @param userEmailAddress User email address for context (optional) (optional)
/// @param userEmailAddressVerified True if the user&#39;s email address was verified (optional) (optional)
/// @param inputFile Input document, or photos of a document, to perform fraud detection on (optional)
/// 
///  code:200 message:"OK"
///
/// @return CMAdvancedFraudDetectionResult*
-(NSURLSessionTask*) documentDetectFraudAdvancedWithUserEmailAddress: (NSString*) userEmailAddress
    userEmailAddressVerified: (NSNumber*) userEmailAddressVerified
    inputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMAdvancedFraudDetectionResult* output, NSError* error)) handler;



@end
